/**
 * Columns at transaction index (Elastic search)
 */
export enum AggTransactionEnum {
  date = "created",
  trx_status = "transaction_status",
  approval_code = "approval_code",
  response_text = "response_text",
  response_code = "response_code",
  merchant_name = "merchant_name",
  merchant_id = "merchant_id",
  taxes = "taxes",
  card_type = "card_type",
  transaction_type = "transaction_type.keyword",
  transaction_status = "transaction_status.keyword",
  publicMerchantId = "merchant_id",
  total_amount = "approved_transaction_amount",
  sale_ticket_number = "sale_ticket_number",
  ticket_number = "ticket_number",
  bank_id = "bankId",
  type = "_type",
  bin_card = "bin_card",
  card_holder_name = "card_holder_name",
  currency_code = "currency_code.keyword",
  ice_value = "ice_value",
  iva_value = "iva_value",
  masked_credit_card = "masked_credit_card",
  metadata = "metadata",
  number_of_months = "number_of_months",
  subscription_id = "subscription_id",
  subtotal_iva = "subtotal_iva",
  subtotal_iva0 = "subtotal_iva0",
  transaction_id = "transaction_id",
  subscription_metadata = "subscription_metadata",
  processor_id = "processor_id",
  processor_name = "processor_name",
  payment_brand = "payment_brand.keyword",
}
