export enum DeferredNamesEnum {
  "D001" = "Diferido corriente",
  "D002" = "Diferido con intereses",
  "D003" = "Diferido sin intereses",
  "D004" = "Tipo de Comercio Gasolinera",
  "D007" = "Diferido especial con interés",
  "D008" = "Tarjeta descuento",
  "D009" = "Diferido especial sin interés",
  "D021" = "Diferido Plus Cuotas",
  "D022" = "Diferido Plus",
  "D01" = "Diferido Cuota Fija con intereses",
  "D02" = "Diferido con meses de gracia con intereses",
  "D03" = "Diferido Pago Mes a Mes con intereses",
  "D04" = "Diferido Cuota Fija sin intereses",
  "D05" = "Diferido con meses de gracia sin intereses",
  "D06" = "Diferido Pago Mes a Mes sin intereses",
  "D07" = "Diferido especial sin intereses",
  "D50" = "Diferido promociones Supermaxi",
}
