/**
 * Transaction Types
 */
export enum TransactionTypeEnum {
  CAPTURE = "CAPTURE",
  CHARGE = "CHARGE",
  CHARGE_WITHOUT_CVV = "chargeWithoutCVV",
  DEFERRED = "DEFERRED",
  DEFFERED = "DEFFERED",
  PREAUTH = "PREAUTHORIZATION",
  REAUTH = "REAUTHORIZATION",
  SALE = "SALE",
  SUBSCRIPTION = "SUBSCRIPTION",
  VOID = "VOID",
  ACCOUNT_VALIDATION = "ACCOUNT_VALIDATION",
  SUBSCRIPTION_CHARGE_VALIDATION = "SUBSCRIPTIONCHARGEVALIDATION",
}

export const TRX_TYPE_SUBSCRIPTION: string[] = [
  TransactionTypeEnum.PREAUTH,
  TransactionTypeEnum.CAPTURE,
];
